### PR TITLE
lesson 4

### PR DESCRIPTION
**Pull request by PerryL17**

### CODE REVIEW

**Comment by ethomp-dev** [comment]
Hey @PerryL17! Please create a Pull Request in your forked repository instead of this one

If you've already completed this step, no need to do anything else! Thanks

**Comment by PerryL17** [comment]
Sorry, I did one last night with a mentor for the lesson that was due
yesterday. Unfortunately I have very little understanding about github.
Does closed mean it was done? Thank you. Perry

**Comment by ethomp-dev** [comment]
@PerryL17 no worries, the base/fork repository structure is new and a little confusing at first

you only need to create Pull Requests inside your forked repository, not "Code the Dream School"

it looks like you have an open Pull Request for [Lesson 4.2](https://github.com/PerryL17/intro-to-programming-eclipse/pull/3), once you merge and close that one you should be all set

let me know if you have any questions 😄

**Comment by PerryL17** [comment]
Thank you so much!

**Pull request closed without merging**
