### PR TITLE
Kenneth Durham pull request

### PR DESCRIPTION
**Pull request by kenldurham**
My first pull request.

### CODE REVIEW

**Comment by ethomp-dev** [comment]
Hey @kenldurham! Please create a Pull Request in your forked repository instead of this one:
https://github.com/kenldurham/intro-to-programming-eclipse/compare/main...kenldurham:lesson-2-1

If you've already completed this step, no need to do anything else! Thanks

**Comment by kenldurham** [comment]
I thought I did. Did I do it wrong? Can you please check if I did
it correctly?

**Comment by kenldurham** [comment]
https://github.com/kenldurham/intro-to-programming-eclipse/pull/1/files

**Comment by ethomp-dev** [comment]
@kenldurham yep, looks like you're all set! You only need to make pull requests in your forked repository going forward.

Also as a note, it looks like you added the new file in the `instructions/` directory instead of the root directory. I would recommend moving `index.html` to the top-level of your project.

**Pull request closed without merging**
