### PR TITLE
Lesson 2.1

### PR DESCRIPTION
**Pull request by JCVF**
added index.html file

### CODE REVIEW

**Comment by ethomp-dev** [comment]
Hey @JCVF! Please create a Pull Request in your forked repository instead of this one:
https://github.com/JCVF/intro-to-programming-eclipse/compare/main...JCVF:lesson-2-1

If you've already completed this step, no need to do anything else! Thanks

**Comment by JCVF** [comment]
So creat a new pull? I’m a bit confused

On May 12, 2021, at 13:01, E Thompson ***@***.***> wrote:

﻿

Closed #12<https://github.com/Code-the-Dream-School/intro-to-programming-eclipse/pull/12>.

**Comment by ethomp-dev** [comment]
hey @JCVF, did you get this figured out or are you still looking for help?

**Comment by JCVF** [comment]
Yeah I figured it out. Also I’m going to be late submitting last week lesson. Had a long work week this passed week.

On Jun 3, 2021, at 12:12, E Thompson ***@***.***> wrote:

﻿

hey @JCVF<https://github.com/JCVF>, did you get this figured out or are you still looking for help?

**Pull request closed without merging**
